# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIOcelotInterface_gen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 922)
        Form.setMinimumSize(QtCore.QSize(400, 0))
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget = ResetpanelBoxWindow(self.tab)
        self.widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(600, 0))
        self.widget.setObjectName("widget")
        self.gridLayout_9.addWidget(self.widget, 0, 0, 2, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_9.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_9.addWidget(self.widget_3, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_start_scan = QtWidgets.QPushButton(self.tab)
        self.pb_start_scan.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_scan.setFont(font)
        self.pb_start_scan.setStyleSheet("color: rgb(85, 255, 127);")
        self.pb_start_scan.setObjectName("pb_start_scan")
        self.horizontalLayout_2.addWidget(self.pb_start_scan)
        self.pb_logbook = QtWidgets.QPushButton(self.tab)
        self.pb_logbook.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_logbook.setFont(font)
        self.pb_logbook.setStyleSheet("color: rgb(85, 255, 255);")
        self.pb_logbook.setObjectName("pb_logbook")
        self.horizontalLayout_2.addWidget(self.pb_logbook)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_help = QtWidgets.QPushButton(self.frame)
        self.pb_help.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_help.setFont(font)
        self.pb_help.setObjectName("pb_help")
        self.gridLayout_2.addWidget(self.pb_help, 5, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab2)
        self.groupBox.setEnabled(True)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 180))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(14, 109, 245);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setEnabled(True)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setEnabled(True)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.label_datapoints = QtWidgets.QLabel(self.groupBox)
        self.label_datapoints.setEnabled(True)
        self.label_datapoints.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_datapoints.setFont(font)
        self.label_datapoints.setStyleSheet("color: rgb(14, 109, 245);")
        self.label_datapoints.setObjectName("label_datapoints")
        self.verticalLayout_6.addWidget(self.label_datapoints)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sb_tdelay = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_tdelay.sizePolicy().hasHeightForWidth())
        self.sb_tdelay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_tdelay.setFont(font)
        self.sb_tdelay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_tdelay.setMinimum(0.0)
        self.sb_tdelay.setMaximum(99.99)
        self.sb_tdelay.setSingleStep(0.1)
        self.sb_tdelay.setProperty("value", 0.0)
        self.sb_tdelay.setObjectName("sb_tdelay")
        self.verticalLayout_7.addWidget(self.sb_tdelay)
        self.sb_ddelay = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sb_ddelay.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_ddelay.setFont(font)
        self.sb_ddelay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_ddelay.setMinimum(0.0)
        self.sb_ddelay.setSingleStep(0.05)
        self.sb_ddelay.setProperty("value", 0.0)
        self.sb_ddelay.setObjectName("sb_ddelay")
        self.verticalLayout_7.addWidget(self.sb_ddelay)
        self.sb_nreadings = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_nreadings.setFont(font)
        self.sb_nreadings.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_nreadings.setMinimum(1)
        self.sb_nreadings.setProperty("value", 1)
        self.sb_nreadings.setObjectName("sb_nreadings")
        self.verticalLayout_7.addWidget(self.sb_nreadings)
        self.sb_datapoints = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_datapoints.setFont(font)
        self.sb_datapoints.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_datapoints.setMinimum(1)
        self.sb_datapoints.setMaximum(1000000)
        self.sb_datapoints.setProperty("value", 1)
        self.sb_datapoints.setObjectName("sb_datapoints")
        self.verticalLayout_7.addWidget(self.sb_datapoints)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.sb_num_iter = QtWidgets.QSpinBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_num_iter.setFont(font)
        self.sb_num_iter.setMaximum(1000)
        self.sb_num_iter.setProperty("value", 50)
        self.sb_num_iter.setObjectName("sb_num_iter")
        self.gridLayout_12.addWidget(self.sb_num_iter, 4, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(14, 109, 245);")
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(14, 109, 245);")
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 4, 0, 1, 1)
        self.cb_select_alg = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_select_alg.setFont(font)
        self.cb_select_alg.setObjectName("cb_select_alg")
        self.gridLayout_12.addWidget(self.cb_select_alg, 2, 1, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_31 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(14, 109, 245);")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_4.addWidget(self.label_31)
        self.sb_scaling_coef = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_scaling_coef.setFont(font)
        self.sb_scaling_coef.setDecimals(3)
        self.sb_scaling_coef.setMinimum(0.0)
        self.sb_scaling_coef.setMaximum(999.0)
        self.sb_scaling_coef.setProperty("value", 1.0)
        self.sb_scaling_coef.setObjectName("sb_scaling_coef")
        self.horizontalLayout_4.addWidget(self.sb_scaling_coef)
        self.verticalLayout_20.addLayout(self.horizontalLayout_4)
        self.cb_set_best_sol = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_set_best_sol.setFont(font)
        self.cb_set_best_sol.setChecked(True)
        self.cb_set_best_sol.setObjectName("cb_set_best_sol")
        self.verticalLayout_20.addWidget(self.cb_set_best_sol)
        self.verticalLayout_12.addWidget(self.groupBox_8)
        self.g_box_isim = QtWidgets.QGroupBox(self.tab2)
        self.g_box_isim.setEnabled(True)
        self.g_box_isim.setMaximumSize(QtCore.QSize(16777215, 90))
        self.g_box_isim.setObjectName("g_box_isim")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.g_box_isim)
        self.verticalLayout_21.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.cb_use_isim = QtWidgets.QCheckBox(self.g_box_isim)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_use_isim.setFont(font)
        self.cb_use_isim.setObjectName("cb_use_isim")
        self.verticalLayout_18.addWidget(self.cb_use_isim)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_23 = QtWidgets.QLabel(self.g_box_isim)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_8.addWidget(self.label_23)
        self.sb_isim_rel_step = QtWidgets.QDoubleSpinBox(self.g_box_isim)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_isim_rel_step.setFont(font)
        self.sb_isim_rel_step.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_isim_rel_step.setDecimals(2)
        self.sb_isim_rel_step.setMinimum(0.01)
        self.sb_isim_rel_step.setMaximum(1000.0)
        self.sb_isim_rel_step.setSingleStep(0.25)
        self.sb_isim_rel_step.setProperty("value", 5.0)
        self.sb_isim_rel_step.setObjectName("sb_isim_rel_step")
        self.horizontalLayout_8.addWidget(self.sb_isim_rel_step)
        self.verticalLayout_18.addLayout(self.horizontalLayout_8)
        self.verticalLayout_21.addLayout(self.verticalLayout_18)
        self.verticalLayout_12.addWidget(self.g_box_isim)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 180))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setContentsMargins(12, 0, -1, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setEnabled(False)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setEnabled(False)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_hyper_file = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_hyper_file.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_hyper_file.sizePolicy().hasHeightForWidth())
        self.pb_hyper_file.setSizePolicy(sizePolicy)
        self.pb_hyper_file.setMaximumSize(QtCore.QSize(16777215, 43))
        self.pb_hyper_file.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pb_hyper_file.setFont(font)
        self.pb_hyper_file.setObjectName("pb_hyper_file")
        self.verticalLayout_2.addWidget(self.pb_hyper_file)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.sb_seed_iter = QtWidgets.QSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_seed_iter.setFont(font)
        self.sb_seed_iter.setMinimum(1)
        self.sb_seed_iter.setProperty("value", 5)
        self.sb_seed_iter.setObjectName("sb_seed_iter")
        self.verticalLayout_2.addWidget(self.sb_seed_iter)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.cb_use_live_seed = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_use_live_seed.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_use_live_seed.setFont(font)
        self.cb_use_live_seed.setObjectName("cb_use_live_seed")
        self.gridLayout_3.addWidget(self.cb_use_live_seed, 1, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pb_save_as = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_save_as.sizePolicy().hasHeightForWidth())
        self.pb_save_as.setSizePolicy(sizePolicy)
        self.pb_save_as.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_save_as.setFont(font)
        self.pb_save_as.setObjectName("pb_save_as")
        self.horizontalLayout_7.addWidget(self.pb_save_as)
        self.pb_load = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_load.sizePolicy().hasHeightForWidth())
        self.pb_load.setSizePolicy(sizePolicy)
        self.pb_load.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_load.setFont(font)
        self.pb_load.setObjectName("pb_load")
        self.horizontalLayout_7.addWidget(self.pb_load)
        self.pb_rewrite = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_rewrite.sizePolicy().hasHeightForWidth())
        self.pb_rewrite.setSizePolicy(sizePolicy)
        self.pb_rewrite.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_rewrite.setFont(font)
        self.pb_rewrite.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pb_rewrite.setObjectName("pb_rewrite")
        self.horizontalLayout_7.addWidget(self.pb_rewrite)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.preset_layout = QtWidgets.QHBoxLayout()
        self.preset_layout.setObjectName("preset_layout")
        self.gridLayout_4.addLayout(self.preset_layout, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.tab3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.verticalLayout_10.addLayout(self.verticalLayout_19)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 400))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_15.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_15.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_15.addWidget(self.label_20)
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_15.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_15.addWidget(self.label_29)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(14, 109, 245);")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_15.addWidget(self.label_21)
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_15.addWidget(self.label_26)
        self.gridLayout_11.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.le_a = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_a.setEnabled(True)
        self.le_a.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_a.setFont(font)
        self.le_a.setText("")
        self.le_a.setObjectName("le_a")
        self.verticalLayout_16.addWidget(self.le_a)
        self.le_b = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_b.setEnabled(True)
        self.le_b.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_b.setFont(font)
        self.le_b.setObjectName("le_b")
        self.verticalLayout_16.addWidget(self.le_b)
        self.le_c = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_c.setEnabled(True)
        self.le_c.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_c.setFont(font)
        self.le_c.setObjectName("le_c")
        self.verticalLayout_16.addWidget(self.le_c)
        self.le_d = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_d.setEnabled(True)
        self.le_d.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_d.setFont(font)
        self.le_d.setObjectName("le_d")
        self.verticalLayout_16.addWidget(self.le_d)
        self.le_e = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_e.setEnabled(True)
        self.le_e.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_e.setFont(font)
        self.le_e.setObjectName("le_e")
        self.verticalLayout_16.addWidget(self.le_e)
        self.le_obf = QtWidgets.QLineEdit(self.groupBox_7)
        self.le_obf.setEnabled(True)
        self.le_obf.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.le_obf.setFont(font)
        self.le_obf.setObjectName("le_obf")
        self.verticalLayout_16.addWidget(self.le_obf)
        self.sb_max_pen = QtWidgets.QSpinBox(self.groupBox_7)
        self.sb_max_pen.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sb_max_pen.setFont(font)
        self.sb_max_pen.setMinimum(-1000)
        self.sb_max_pen.setMaximum(1000)
        self.sb_max_pen.setProperty("value", 100)
        self.sb_max_pen.setObjectName("sb_max_pen")
        self.verticalLayout_16.addWidget(self.sb_max_pen)
        self.gridLayout_11.addLayout(self.verticalLayout_16, 0, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.rb_minimize = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rb_minimize.setFont(font)
        self.rb_minimize.setObjectName("rb_minimize")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb_minimize)
        self.horizontalLayout_12.addWidget(self.rb_minimize)
        self.rb_maximize = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rb_maximize.setFont(font)
        self.rb_maximize.setChecked(True)
        self.rb_maximize.setObjectName("rb_maximize")
        self.buttonGroup.addButton(self.rb_maximize)
        self.horizontalLayout_12.addWidget(self.rb_maximize)
        self.gridLayout_11.addLayout(self.horizontalLayout_12, 2, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(14, 109, 245);")
        self.label_38.setObjectName("label_38")
        self.gridLayout_11.addWidget(self.label_38, 1, 0, 1, 1)
        self.cb_statistics = QtWidgets.QComboBox(self.groupBox_7)
        self.cb_statistics.setMinimumSize(QtCore.QSize(0, 32))
        self.cb_statistics.setObjectName("cb_statistics")
        self.gridLayout_11.addWidget(self.cb_statistics, 1, 2, 1, 1)
        self.cb_use_predef = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cb_use_predef.setFont(font)
        self.cb_use_predef.setChecked(False)
        self.cb_use_predef.setObjectName("cb_use_predef")
        self.gridLayout_11.addWidget(self.cb_use_predef, 3, 0, 1, 1)
        self.pb_edit_obj_func = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_edit_obj_func.sizePolicy().hasHeightForWidth())
        self.pb_edit_obj_func.setSizePolicy(sizePolicy)
        self.pb_edit_obj_func.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb_edit_obj_func.setFont(font)
        self.pb_edit_obj_func.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pb_edit_obj_func.setStyleSheet("color: rgb(85, 255, 255); font-size: 18pt;")
        self.pb_edit_obj_func.setObjectName("pb_edit_obj_func")
        self.gridLayout_11.addWidget(self.pb_edit_obj_func, 3, 2, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab3)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_13.addWidget(self.label_15)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.le_alarm = QtWidgets.QLineEdit(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_alarm.setFont(font)
        self.le_alarm.setObjectName("le_alarm")
        self.horizontalLayout_9.addWidget(self.le_alarm)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.label_alarm = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_alarm.setFont(font)
        self.label_alarm.setObjectName("label_alarm")
        self.horizontalLayout_9.addWidget(self.label_alarm)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.sb_alarm_min = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_alarm_min.sizePolicy().hasHeightForWidth())
        self.sb_alarm_min.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sb_alarm_min.setFont(font)
        self.sb_alarm_min.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_alarm_min.setMinimum(-99999999.99)
        self.sb_alarm_min.setMaximum(99999999.99)
        self.sb_alarm_min.setSingleStep(0.1)
        self.sb_alarm_min.setProperty("value", 0.0)
        self.sb_alarm_min.setObjectName("sb_alarm_min")
        self.horizontalLayout_6.addWidget(self.sb_alarm_min)
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.sb_alarm_max = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_alarm_max.sizePolicy().hasHeightForWidth())
        self.sb_alarm_max.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sb_alarm_max.setFont(font)
        self.sb_alarm_max.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_alarm_max.setMinimum(-99999999.99)
        self.sb_alarm_max.setMaximum(99999999.99)
        self.sb_alarm_max.setSingleStep(0.1)
        self.sb_alarm_max.setObjectName("sb_alarm_max")
        self.horizontalLayout_6.addWidget(self.sb_alarm_max)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sb_alarm_timeout = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_alarm_timeout.sizePolicy().hasHeightForWidth())
        self.sb_alarm_timeout.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sb_alarm_timeout.setFont(font)
        self.sb_alarm_timeout.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_alarm_timeout.setMinimum(0.0)
        self.sb_alarm_timeout.setMaximum(100.0)
        self.sb_alarm_timeout.setSingleStep(0.1)
        self.sb_alarm_timeout.setProperty("value", 2.0)
        self.sb_alarm_timeout.setObjectName("sb_alarm_timeout")
        self.horizontalLayout_10.addWidget(self.sb_alarm_timeout)
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.gridLayout_10.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab4)
        self.horizontalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.data_layout = QtWidgets.QVBoxLayout()
        self.data_layout.setObjectName("data_layout")
        self.frame_2 = QtWidgets.QFrame(self.tab4)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("border-color: blue;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.browser_data_slider = QtWidgets.QSlider(self.frame_2)
        self.browser_data_slider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.browser_data_slider.setStyleSheet("QSlider::groove:horizontal{\n"
"border: 1px solid #637EB8;\n"
"background: white;\n"
"height: 7px;\n"
"border-radius: 3px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #ABC7EC, stop: 1 #154A98);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #154A98;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::handle:horizontal{\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 #fff, stop:1 #b3b4b6);\n"
"border: 1px solid #777;\n"
"width: 10px;\n"
"margin-top: -4px;\n"
"margin-bottom: -4px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"/*Verticales*/\n"
"QSlider::groove:vertical{\n"
"border: 1px solid #637EB8;\n"
"background: white;\n"
"width:7px;\n"
"height: 55px;\n"
"border-radius: 3px;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #ABC7EC, stop: 1 #154A98);\n"
"border: 1px solid #154A98;\n"
"width: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"width: 7px;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::handle:vertical{\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 #fff, stop:1 #ABC7EC);\n"
"border: 1px solid #777;\n"
"height: 5px;\n"
"margin-left: -4px;\n"
"margin-right: -4px;\n"
"border-radius: 2px;\n"
"}\n"
"/*Horizontales y Verticales*/\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover{\n"
"border: 1px solid #154A98;\n"
"border-radius: 3px;\n"
"}")
        self.browser_data_slider.setMaximum(10)
        self.browser_data_slider.setPageStep(10)
        self.browser_data_slider.setOrientation(QtCore.Qt.Horizontal)
        self.browser_data_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.browser_data_slider.setTickInterval(1)
        self.browser_data_slider.setObjectName("browser_data_slider")
        self.verticalLayout.addWidget(self.browser_data_slider)
        self.browser_data_table = QtWidgets.QTableWidget(self.frame_2)
        self.browser_data_table.setMinimumSize(QtCore.QSize(200, 0))
        self.browser_data_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.browser_data_table.setObjectName("browser_data_table")
        self.browser_data_table.setColumnCount(0)
        self.browser_data_table.setRowCount(0)
        self.verticalLayout.addWidget(self.browser_data_table)
        self.browser_restore_btn = QtWidgets.QPushButton(self.frame_2)
        self.browser_restore_btn.setEnabled(False)
        self.browser_restore_btn.setMinimumSize(QtCore.QSize(0, 32))
        self.browser_restore_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.browser_restore_btn.setFont(font)
        self.browser_restore_btn.setStyleSheet("color: orange")
        self.browser_restore_btn.setObjectName("browser_restore_btn")
        self.verticalLayout.addWidget(self.browser_restore_btn)
        self.data_layout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.tab4)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.browser_objhist_plot_panel = QtWidgets.QWidget(self.frame_3)
        self.browser_objhist_plot_panel.setStyleSheet("")
        self.browser_objhist_plot_panel.setObjectName("browser_objhist_plot_panel")
        self.verticalLayout_4.addWidget(self.browser_objhist_plot_panel)
        self.data_layout.addWidget(self.frame_3)
        self.data_layout.setStretch(0, 1)
        self.data_layout.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.data_layout)
        self.plots_layout = QtWidgets.QVBoxLayout()
        self.plots_layout.setObjectName("plots_layout")
        self.label = QtWidgets.QLabel(self.tab4)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plots_layout.addWidget(self.label)
        self.browser_obj_plot_panel = QtWidgets.QWidget(self.tab4)
        self.browser_obj_plot_panel.setObjectName("browser_obj_plot_panel")
        self.plots_layout.addWidget(self.browser_obj_plot_panel)
        self.label_4 = QtWidgets.QLabel(self.tab4)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.plots_layout.addWidget(self.label_4)
        self.browser_dev_plot_panel = QtWidgets.QWidget(self.tab4)
        self.browser_dev_plot_panel.setObjectName("browser_dev_plot_panel")
        self.plots_layout.addWidget(self.browser_dev_plot_panel)
        self.horizontalLayout_3.addLayout(self.plots_layout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.tabWidget.addTab(self.tab4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ocelot Interface"))
        self.pb_start_scan.setText(_translate("Form", "Start optimization"))
        self.pb_logbook.setText(_translate("Form", "Logbook"))
        self.pb_help.setText(_translate("Form", "Help/Docs"))
        self.pushButton_3.setText(_translate("Form", "GP 2D Heatmap"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Optimization Scan Panel"))
        self.label_3.setText(_translate("Form", "Scanner Setup and Options Panel"))
        self.groupBox.setTitle(_translate("Form", "Scanner Timing"))
        self.label_2.setText(_translate("Form", "Settle Time (seconds)          "))
        self.label_6.setText(_translate("Form", "Interval between readings (seconds)"))
        self.label_30.setText(_translate("Form", "Number of readings"))
        self.label_datapoints.setText(_translate("Form", "Data Points"))
        self.label_7.setText(_translate("Form", "Cycle Period = "))
        self.groupBox_8.setTitle(_translate("Form", "Scanner Parameters"))
        self.label_27.setText(_translate("Form", "Select Optimiser Algorithm "))
        self.label_25.setText(_translate("Form", "Number Iterations"))
        self.label_31.setText(_translate("Form", "Scaling Coeficient"))
        self.sb_scaling_coef.setToolTip(_translate("Form", "Scales the step size by this factor"))
        self.cb_set_best_sol.setText(_translate("Form", "Set Best Solution After Optimization"))
        self.g_box_isim.setTitle(_translate("Form", "Simplex/Scipy Scanner Setup"))
        self.cb_use_isim.setToolTip(_translate("Form", "This is only used if the device is not in the LenghtScale list. Try to create as a % of the limit range"))
        self.cb_use_isim.setText(_translate("Form", "Use Initial Simplex/Step [step =(Max - Min) x RelStep[%]]"))
        self.label_23.setText(_translate("Form", "Relative Step in %"))
        self.sb_isim_rel_step.setToolTip(_translate("Form", "This is only used if the device is not in the LenghtScale list. Try to create as a % of the limit range"))
        self.groupBox_2.setTitle(_translate("Form", "GP Scanner Setup"))
        self.label_9.setText(_translate("Form", "GP Hyperparameter File     "))
        self.label_8.setText(_translate("Form", "GP Seed File"))
        self.label_10.setText(_translate("Form", "Iterations of Seed"))
        self.pb_hyper_file.setText(_translate("Form", "HyperFile"))
        self.cb_use_live_seed.setText(_translate("Form", "Use Live Simplex Seed Mode"))
        self.groupBox_5.setTitle(_translate("Form", "Configuration Files"))
        self.pb_save_as.setToolTip(_translate("Form", "Save current Ocelot configuration for later usage"))
        self.pb_save_as.setText(_translate("Form", "Save As"))
        self.pb_load.setToolTip(_translate("Form", "Load saved Ocelot configuration for usage"))
        self.pb_load.setText(_translate("Form", "Load"))
        self.pb_rewrite.setToolTip(_translate("Form", "Save the current state as the default when opening Ocelot"))
        self.pb_rewrite.setText(_translate("Form", "Rewrite Default"))
        self.groupBox_3.setTitle(_translate("Form", "Load Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "Scan Setup Panel"))
        self.label_18.setText(_translate("Form", "Objective and Alarm Function Setup"))
        self.groupBox_7.setTitle(_translate("Form", "Objective Function"))
        self.label_16.setText(_translate("Form", "PV: A"))
        self.label_19.setText(_translate("Form", "PV: B"))
        self.label_20.setText(_translate("Form", "PV: C"))
        self.label_28.setText(_translate("Form", "PV: D"))
        self.label_29.setText(_translate("Form", "PV: E"))
        self.label_21.setText(_translate("Form", "Objective Function:"))
        self.label_26.setText(_translate("Form", "Max Penalty"))
        self.le_obf.setToolTip(_translate("Form", "<html><head/><body><p>Option 1: Type a PV here.</p><p>Option 2:</p><p>- Uncheck the &quot;Use predefined Objective Function&quot; box</p><p>- Fill in PV A...E with PVs</p><p>- Use as Objective Function a formula such as:</p><p>---- np.mean(A-B)</p><p>---- np.mean(A)/np.stdev(B)</p></body></html>"))
        self.le_obf.setText(_translate("Form", "A"))
        self.rb_minimize.setText(_translate("Form", "Minimize Signal"))
        self.rb_maximize.setText(_translate("Form", "Maximize Signal"))
        self.label_38.setText(_translate("Form", "Statistical Method:"))
        self.cb_use_predef.setToolTip(_translate("Form", "If checked, it uses the Target function in the Python script given by Edit Objective Function button"))
        self.cb_use_predef.setText(_translate("Form", "Use Predefined Objective Function"))
        self.pb_edit_obj_func.setText(_translate("Form", "Edit Objective Function"))
        self.groupBox_6.setToolTip(_translate("Form", "Useful to interrupt the scan in case a PV defined by \"Alarm 1\" goes out of range defined by limits."))
        self.groupBox_6.setTitle(_translate("Form", "Machine Status"))
        self.label_13.setText(_translate("Form", "Alarm 1"))
        self.label_14.setText(_translate("Form", "Limits:     "))
        self.label_15.setText(_translate("Form", "Wait"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">Value:    </span></p></body></html>"))
        self.label_alarm.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">0</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "Min   "))
        self.label_22.setText(_translate("Form", "          Max    "))
        self.label_24.setText(_translate("Form", "sec after recovering                             "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("Form", "Objective Function"))
        self.label_5.setText(_translate("Form", "Data Explorer:"))
        self.browser_data_slider.setToolTip(_translate("Form", "Use this to navigate the data points"))
        self.browser_restore_btn.setText(_translate("Form", "Restore Devices"))
        self.label_11.setText(_translate("Form", "Objective Function Histogram Monitor:"))
        self.label.setText(_translate("Form", "Objective Function Monitor:"))
        self.label_4.setText(_translate("Form", "Objective Function Monitor:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("Form", "Data Browser"))

from resetpanel.resetpanelbox import ResetpanelBoxWindow

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

