# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIresetpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 850)
        Form.setMinimumSize(QtCore.QSize(400, 0))
        Form.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        Form.setStyleSheet("background-color: white")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updateReference = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.updateReference.setFont(font)
        self.updateReference.setStyleSheet("color: orange")
        self.updateReference.setObjectName("updateReference")
        self.horizontalLayout.addWidget(self.updateReference)
        self.resetAll = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.resetAll.setFont(font)
        self.resetAll.setStyleSheet("color: red")
        self.resetAll.setObjectName("resetAll")
        self.horizontalLayout.addWidget(self.resetAll)
        self.check = QtWidgets.QPushButton(Form)
        self.check.setObjectName("check")
        self.horizontalLayout.addWidget(self.check)
        self.uncheck = QtWidgets.QPushButton(Form)
        self.uncheck.setObjectName("uncheck")
        self.horizontalLayout.addWidget(self.uncheck)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_extra = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_extra.sizePolicy().hasHeightForWidth())
        self.pb_extra.setSizePolicy(sizePolicy)
        self.pb_extra.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(14)
        self.pb_extra.setFont(font)
        self.pb_extra.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pb_extra.setObjectName("pb_extra")
        self.horizontalLayout_2.addWidget(self.pb_extra)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.layout_quick_add = QtWidgets.QHBoxLayout()
        self.layout_quick_add.setObjectName("layout_quick_add")
        self.gridLayout.addLayout(self.layout_quick_add, 5, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Reset Panel"))
        self.updateReference.setText(_translate("Form", "Update reference "))
        self.resetAll.setText(_translate("Form", "Reset All"))
        self.check.setText(_translate("Form", "Check"))
        self.uncheck.setText(_translate("Form", "Uncheck"))
        self.pb_extra.setText(_translate("Form", "abs"))
        self.label.setText(_translate("Form", "Middle click a PV then the table to add your favorite device!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
